#ifndef PROJECT_TEMPLATE_SCANNER_HPP
#define PROJECT_TEMPLATE_SCANNER_HPP

#include "parser.hpp" // Generated by Bison.

#ifndef yyFlexLexerOnce
#  include <FlexLexer.h>
#endif // yyFlexLexerOnce

#include <iosfwd> // For std::istream and std::ostream.

namespace project_template
{
    class driver;

    class scanner : public yyFlexLexer
    {
    public:
        auto yylex(driver& _driver) -> yy::parser::symbol_type;
    }; // class scanner
} // namespace project_template

#endif // PROJECT_TEMPLATE_SCANNER_HPP
